### ISSUE TITLE
Dinner Recipe 

### ISSUE THREAD

**Issue by dhruvkc** [IntroToCode/RecipesCodemates8#1]
@boncobee is handling this portion of the deliverable.

**Comment by boncobee** [comment]
I'm going to add in a Korean spicy pork recipe unless there are any objections?

**Comment by dhruvkc** [comment]
That sounds good, could you highlight tofu as a vegetarian substitute if applicable?

**Comment by wyattmdavis** [comment]
I just added in a dessert as a separate branch. we can merge once reviewed and approved!

**Comment by boncobee** [comment]
Sounds great! (also will add tofu as a vegetarian substitute)

**Comment by dhruvkc** [comment]
how goes this? getting hungry just thinking about it!

**Comment by wyattmdavis** [comment]
we had a bit of confusion with so many pull requests and an attempt to revert code, but I think we're good to go now!

@boncobee are you good with closing this issue?

**Comment by wyattmdavis** [comment]
we had a bit of confusion with so many pull requests and an attempt to revert code, but I think we're good to go now! Just merged the final pull request so will close this issue. 

Great work team!
