### ISSUE TITLE
Lunch Recipe

### ISSUE THREAD

**Issue by wyattmdavis** [IntroToCode/RecipesCodemates8#11]
## 💬 Discussion topic

Collaboration on lunch

## ❗ Potential issues

Looks like we don't have enough collaboration on the Lunch Recipe. 
## 👥 People to consult

@baldjeff @boncobee @jzofficial66 @dhruvkc 

## 📃 Details

Can we assign out/delineate work per the assignment?
<img width="579" alt="Screen Shot 2020-10-22 at 6 00 54 PM" src="https://user-images.githubusercontent.com/72418744/96944761-986c1b80-1490-11eb-86de-103a95674804.png">

**Comment by wyattmdavis** [comment]
@jzofficial66 looks like you're in charge of the lunch recipe! I was a bit confused by the pull request to revert changes - can you give me an update on where we are with lunch? Just trying to catch up after missing class last week! 🤦🏼‍♀️🙏🏼 Thank you!

**Comment by jzofficial66** [comment]
Hey @wyattmdavis! I have opened a pull request for the lunch already. Just waiting on people to finish reviewing.
