### ISSUE TITLE
Dinner is Missing!

### ISSUE THREAD

**Issue by wyattmdavis** [IntroToCode/RecipesCodemates8#14]
## 💬 Discussion topic

Need to add back in Dinner Recipe

## ❗ Potential issues

I took a look at the pull requests, and @boncobee dinner recipe was in the "dinner_update_boncobee_v1" branch, which we ended up closing due to a conflict. I don't see any other pull requests with a dinner recipe, so it makes sense that we only have Strawberry Shortcake for dinner right now. Childhood dream, but not very nutritious!

## 👥 People to consult

@boncobee can you double check and confirm that my understanding of the issue is correct?
@jzofficial66 @baldjeff @dhruvkc does anyone still need to be an approver or a merger? Let me know and i'll add you

## 📃 Details

Text

**Comment by boncobee** [comment]
Thanks for fixing this--wasn't sure why there were issues with merging the v1 and v2 of the dinner request and updates.
