### ISSUE TITLE
breakfast_recipe_assignment

### ISSUE THREAD

**Issue by boncobee** [IntroToCode/RecipesCodemates8#2]
## 💬 Discussion topic

Jeff Liew (@baldjeff) and Dhruva (@dhruvkc  assigned breakfast

## ❗ Potential issues

Coordinate so that there is no overlap

## 👥 People to consult

@baldjeff + @dhruvkc 

## 📃 Details

Approvers for the pull requests for breakfast will be Joseph Zhang (@jzofficial66) and Joe Choi (@boncobee)

**Comment by baldjeff** [comment]
I wrote the recipe
@dhruvkc Can you please follow through to make sure the pull gets pushed?

**Comment by boncobee** [comment]
I think @baldjeff might have mistakenly auto/self-approved his own changes instead of submitting as a pull request right?

**Comment by dhruvkc** [comment]
Is "Eggs a la Scramble" a good recipe name or does it sound too fancy?

**Comment by dhruvkc** [comment]
> I think @baldjeff might have mistakenly auto/self-approved his own changes instead of submitting as a pull request right?

Agreed should @baldjeff make any changes so he can be included on the pull request as per the assignment?

**Comment by boncobee** [comment]
I think so, if he can make another pull request @jzofficial66  and I can review and then merge

**Comment by wyattmdavis** [comment]
Hey everyone! wasn't able to make it to class this week, but i'm on the team! I just submitted a pull request with some formatting changes for the breakfast recipe. please take a look!
