### ISSUE TITLE
Lunch Recipe 

### ISSUE THREAD

**Issue by dhruvkc** [IntroToCode/RecipesCodemates8#3]
@jzofficial66 is handling the Lunch portion of this deliverable.

**Comment by jzofficial66** [comment]
Got it. Will do! What type of lunch do you all want?

**Comment by boncobee** [comment]
Something with lots of protein!

**Comment by jzofficial66** [comment]
Ok. Here are two choices: 

1. Garlic butter steak bites
2. Honey garlic chicken

What are you thinking?

**Comment by boncobee** [comment]
#2 FOSHO

**Comment by dhruvkc** [comment]
Hey team, 

I'm vegetarian, but dairy and eggs are ok. Can we please consider a vegetarian option or alternative? Thanks!

**Comment by jzofficial66** [comment]
Okay got it. I'll add a tofu alternative for the chicken. That cool with you, @dhruvkc?

**Comment by dhruvkc** [comment]
> Okay got it. I'll add a tofu alternative for the chicken. That cool with you, @dhruvkc?

Really appreciate it @jzofficial66, that'd be awesome! Tofu, tempeh, etc -- whatever is easiest for you.
